apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ces-security-headers
spec:
  headers:
    customResponseHeaders:
      # style-src: allow all styles as most dogus load styles from external sources
      # script-src: allow unsafe-eval for Nexus, SCM and EasyRedmine
      Content-Security-Policy: >-
        default-src 'self';
        script-src 'self' 'unsafe-eval';
        style-src * 'unsafe-inline';
        img-src 'self' data: blob:;
        font-src 'self' data:;
        connect-src 'self';
        frame-ancestors 'self';
        base-uri 'self';
        form-action 'self'
      Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "0"
      Cross-Origin-Opener-Policy: "same-origin"
      Cross-Origin-Resource-Policy: "same-origin"
      Permissions-Policy: "geolocation=(), microphone=(), camera=(), payment=()"