apiVersion: v1
kind: ConfigMap
metadata:
  name: initial-exposed-ports-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s.cloudogu.com/component.config: {{ .Release.Name }}
data:
  values: |-
    traefik:
      ports:
{{ .Values.traefik.ports | toYaml | nindent 8 }}
