# Configmap for adding custom headers before sending traffic to backends
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-gateway-ces-config-conf
data:
  subfilters.conf: |-
{{ .Files.Get "ces-config/subfilters.conf" | indent 4 }}
  errors.conf: |-
{{ .Files.Get "ces-config/errors.conf" | indent 4 }}