apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ces-chain
spec:
  chain:
    middlewares:
      - name: ces-accept-encoding-identity
      - name: ces-rewrite
      # ces-nonce remains disabled until csp headers are enabled again
      # - name: ces-nonce
      - name: ces-security-headers
      - name: ces-compress
